name: PureEntities
main: milk\pureentities\PureEntities
version: 1.1.0
api: [3.0.0]

load: STARTUP
author: LeinneSW
description: Implement all MCBE entities
website: https://github.com/LeinneSW/PureEntities
commands: []